### ISSUE TITLE
Feature Request: Override onAuthenticationHelp to allow for actions on "finger moved too fast"

### ISSUE THREAD

**Issue by gerges** [ztc1997/Fingerprint2Sleep#2]
The Google Pixel now supports "swipe for notifications panel" on the fingerprint reader. Although Fingerprint2Sleep can do something similar, it currently only works on successful fingerprints. I wanted to add the ability to catch "finger moved too fast" which is what usually occurs when swiping your finger over the reader.

**Comment by ztc1997** [comment]
That is a good idea to catch "finger moved too fast", but I would like to add the slide as another event, the user can choose to perform to another action, rather than responding as a tap event, I will add it to the new version.

**Comment by gerges** [comment]
Any idea when you'll be releasing this new version? I'm anxious to get better "swipe for notifications tray" in the hands of Nexus6P oweners

**Comment by gerges** [comment]
Any idea when that will be coming out? I'm anxious to get this in the hands
of Nexus 6p owners missing out on the swipe feature
