### ISSUE TITLE
Conflict with other app

### ISSUE THREAD

**Issue by ja-som** [ztc1997/Fingerprint2Sleep#20]
Hi, I have a conflict with other app when it ask for unlock with fingerprint.

App is Call Recorder https://play.google.com/store/apps/details?id=com.skvalex.callrecorder

When I open the app, it asks for fingerprint, but when I use it, it locks my device...

It is possible to add some blacklist to your app?

Thanks

**Comment by ztc1997** [comment]
Thank you for you suggestion. I have noticed this problem and will soon add the blacklist feature.

**Comment by ztc1997** [comment]
d7de192a Auto retry blacklist has been added in version 0.9.0.
