### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by bezuhv** [ztc1997/Fingerprint2Sleep#41]
exceptions according to programs as there is no opportunity to enter bank programs or others which are protected by the scanner of prints are necessary.

**Comment by ztc1997** [comment]
@bezuhv Please tell me your device model and system version.

**Comment by bezuhv** [comment]
Redmi 4, Android 6.0.1

**Comment by ztc1997** [comment]
Please upgrade to 0.12.0, add the associated apps to the blacklist, and retry.

**Comment by bezuhv** [comment]
Ok, it work right.  -- _________________Виталий Безухhttp://mssg.me/bezuhv/14.02.2017, 16:51, "Alex Zhang" <notifications@github.com>:Please upgrade to 0.12.0, add the associated apps to the blacklist, and retry.
